config/routes.rb
FacebookClone::Application.routes.draw do
  get "static_pages/home"
  get "friendships/create"
  get "friendships/destroy"
  resources :users do
    resources :friendships
    resources :wall_posts
    resources :posts
  end
  resources :posts
  resources :friendships
  resources :wall_posts
  resources :sessions, only: [:new, :create, :destroy]
  match '/sign_up', to: 'users#new', via: 'get'
  match '/sign_in', to: 'sessions#new', via: 'get'
  match '/sign_out', to: 'sessions#destroy', via: 'delete'
  root 'static_pages#home'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User", foreign_key: 'friend_id'
  validates :user_id, :friend_id, presence: true
  
  #status codes
  ACCEPTED = 0
  REQUESTED = 1
  PENDING = 2
  
  def accept
    Friendship.accept(user_id, friend_id)
  end
  
  def unfriend
    Friendship.unfriend(user_id, friend_id)
  end
  
  class << self
    def exists?(user, friend)
      not conn(user, friend).nil?
    end
    
    def request(user, friend)
      transaction do
        create!(user: user, friend: friend, status: PENDING)
        create!(user: friend, friend: user, status: REQUESTED)
      end
    end
    
    def accept(user, friend)
      transaction do
        accepted_at = Time.now
        conn(user, friend).update_attributes(status: ACCEPTED, accepted_at: accepted_at)
        conn(friend, user).update_attributes(status: ACCEPTED, accepted_at: accepted_at)
      end
    end
    
    def unfriend(user, friend)
      transaction do
        destroy(conn(user, friend))
        destroy(conn(friend, user))
      end
    end
    
    def conn(user, friend)
      find_by_user_id_and_friend_id(user, friend)
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 200 }
  validates :user_id, presence: true
  
  def self.friends_posts(user)
    friends_ids = "SELECT friend_id FROM friendships WHERE user_id = :user_id AND status = 0"
    where("user_id IN (#{friends_ids}) OR user_id = :user_id", user_id: user.id).order("created_at DESC")
  end
  
  def self.wall_posts(user)
    friends_ids = "SELECT friend_id FROM friendships 
          WHERE user_id = :user_id AND status = 0"
    where("(user_id IN (#{friends_ids}) AND type = 'WallPost') 
          OR user_id = :user_id", user_id: user.id).order("created_at DESC")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :create_auth_token
  has_many :friendships
  has_many :friends, through: :friendships, conditions: [%(status = ?), Friendship::ACCEPTED]
  has_many :requested_friends, through: :friendships, source: :friend, conditions: [%(status = ?), Friendship::REQUESTED]
  has_many :posts  
  has_many :wall_posts

  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  
  def User.generate_token
    SecureRandom.urlsafe_base64
  end
  
  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  def feed
    Post.friends_posts(self)
  end
  
  def wall_feed
    Post.wall_posts(self)
  end
  
  private
  
  def create_auth_token
    self.auth_token = User.hash(User.generate_token)
  end
end

app/models/wall_post.rb
class WallPost < Post
  belongs_to :user
  belongs_to :friend, class_name: "User", foreign_key: 'friend_id'
  
  validates :content, presence: true, length: { maximum: 200 }
  validates :friend_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?
  
  def sign_in(user)
    auth_token = User.generate_token
    user.update_attribute(:auth_token, User.hash(auth_token))
    cookies.permanent[:auth_token] = auth_token
    current_user = user
  end
  
  def current_user=(user)
    @current_user ||= user
  end
  
  def current_user
    auth_token = User.hash(cookies[:auth_token])
    @current_user ||= User.find_by_auth_token(auth_token) if cookies[:auth_token]
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def signed_in
    unless signed_in?
      flash[:error] = 'Please sign in.'
      redirect_to sign_in_path
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_filter :authorize_user, only: [:edit, :update]
  
  def index
    @user = User.find(params[:user_id])
    @friends = @user.friends
  end
  
  def create
    other_user = User.find(params[:user_id])
    Friendship.request(current_user, other_user)
    redirect_to other_user
  end

  def edit
    @friendship = Friendship.find(params[:id])
    @requested_friend = @friendship.friend
  end
  
  def update
    friendship = Friendship.find(params[:id])
    case params[:commit]
    when "Accept"
      friendship.accept
    when "Decline"
      friendship.unfriend
    end
    redirect_to current_user
  end

  def destroy
    other_user = User.find(params[:user_id])
    if Friendship.exists?(current_user, other_user)
      friendship = Friendship.conn(current_user, other_user)
      friendship.unfriend
    end
  end
  
  def authorize_user
    @friendship = Friendship.find(params[:id])
    unless @friendship.status == Friendship::REQUESTED and @friendship.user == current_user
      flash[:error] = 'Not Authorized'
      redirect_to current_user
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def create
    @post = current_user.posts.build(post_params)
    @post.save
    redirect_to current_user
  end
  
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      sign_in user
      flash[:success] = 'Success'
      redirect_to user
    else
      flash.now[:error] = 'Error'
      render 'new'
    end
  end
  
  def destroy
    current_user.update_attribute(:auth_token, User.hash(User.generate_token))
    cookies.delete :auth_toke
    redirect_to sign_in_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :signed_in
  def home
    @feed = current_user.feed
    @post = current_user.posts.build
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in, only: [:index, :show]
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @friendship = Friendship.conn(current_user, @user)
    @wall_feed = @user.wall_feed
    @post = current_user.posts.build if signed_in?
    @wall_post = current_user.wall_posts.build
    if current_user == @user
      @requested_friends = current_user.requested_friends
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = 'Success!'
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/wall_posts_controller.rb
class WallPostsController < ApplicationController
  def create
    user = User.find(params[:user_id])
    wallpost = current_user.wall_posts.build(content: params[:wall_post][:content], friend_id: user.id)
    wallpost.save!
    redirect_to user
  end
  
  def wall_post_params
    params.require(:wall_post).permit(:content, friend_id: :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wall_posts_helper.rb
module WallPostsHelper
end

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/friendships/edit.html.erb
<% provide(:title, 'Respond to request') %>
<%= form_for @friendship do |f| %>
  <%= f.submit 'Accept', class: 'button' %>
  <%= f.submit 'Decline', class: 'button alert' %>
<% end %>

app/views/friendships/index.html.erb
<% provide(:title, "#{@user.name}'s friends") %>
<div class="row">
  <div class="large-6 large-centered columns">
    <% @friends.each do |friend| %>
      <div class="row">
        <div class="large-6 large-centered columns">
          <%= link_to friend.name, user_path(friend) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/header' %>
  <%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'My Site', root_path %></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active">
        <% if signed_in? %>
          <%= link_to 'Profile', user_path(current_user) %>
        <% else %>
          <%= link_to 'Sign Up', sign_up_path %>
        <% end %>
      </li>
      <li class="has-dropdown">
        <a href="#">Options</a>
        <ul class="dropdown">
          <li>
            <% unless signed_in? %>
              <%= link_to 'Sign In', sign_in_path %>
            <% else %>
              <%= link_to 'Sign Out', sign_out_path, method: :delete %>
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
  </section>
</nav>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="large-6 large-centered columns push-down-15">
    <% if current_user %>
        <%= form_for @post do |f| %>
          <div class='large-9 columns post-input'>
            <%= f.text_field :content %>
          </div>
          
          <%= f.submit 'Post', class: 'button' %>
        <% end %>
      <% end %>
    <% unless @feed.empty? %>
      <% @feed.each do |item| %>
          <div class="row alert-box secondary">
            <p class="large-3 columns"><%= item.user.name %>
              <% if item.type == 'WallPost' %>
                posted on <%= item.friend.name %>'s wall
              <% end %>
            </p>
            <p class="large-6 columns"><%= item.content %></p>
            <p class="large-3 columns"><%= item.created_at.strftime("Posted at %H:%M") %></p>
          </div>
      <% end %>
   <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'All Users') %>
<% @users.each do |user| %>
  <%= user.name %>
  <%= user.email %><br/>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<div class="container clearfix">
  <div class="container clearfix">
    <h2 class="form-title">Sign up</h2>
    <p>Want to test out the application? Sign in with email 'fred@fred.com' and password 'test'</p>
    <%= form_for @user do |f| %>
      <%= f.text_field :name, class: 'email', placeholder: 'Name' %>
      <%= f.text_field :email, class: 'email', placeholder: 'Email' %>
      <%= f.password_field :password, class: 'password', placeholder: 'Password' %>
      <%= f.password_field :password_confirmation, class: 'password', placeholder: 'Confirm Password' %>
    <%= submit_tag 'Sign In', class: 'sign_in' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% if current_user == @user and !current_user.requested_friends.empty? %>
  <!-- requested friends -->
  <% current_user.requested_friends.each do |requested_friend| %>
     <div class='row alert-box radius'>
       <div class='large-6 columns'>
         <h5><%= requested_friend.name %> wants to be your friend </h5>
       </div>
      <% @friendship = Friendship.conn(current_user, requested_friend) %>
       <div class='large-6 columns'>
         <%= link_to "Respond?", edit_friendship_path(@friendship), class: 'button tiny alert' %>
       </div>
    </div>
  <% end %>
<% end %>
<div class="row push-down-15">
    <div class="large-4 columns text-center alert-box secondary">
      <h3><%= @user.name %></h3>
      <h3><%= @user.email %></h3>
      <% if Friendship.exists?(current_user, @user) %>
        <% if @friendship.status == Friendship::PENDING %>
          <h4> You have sent <%= @user.name %> a friend request </h4>
        <% elsif @friendship.status == Friendship::REQUESTED %>
          <h4> <%= @user.name %> wants to be your friend </h4>
        <% end %>
      <% elsif current_user != @user %>
      <%= link_to 'Add Friend', user_friendships_path(@user), method: :post, class: 'friend request' %>
      <% end %>
      <% unless @user.friends.empty? %>
        <% @user.friends.each do |friend| %>
          <% unless friend == current_user %>
            <h4><%= link_to friend.name, user_path(friend) %> is your friend</h4>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="large-7 large-offset-1 columns">
      <% if current_user == @user %>
        <%= form_for @post do |f| %>
          <div class='large-9 columns post-input'>
            <%= f.text_field :content %>
          </div>
          <%= f.submit 'Post', class: 'button' %>
        <% end %>
      <% else %>
        <%= form_for [@user, @wall_post] do |f| %>
          <div class='large-9 columns post-input'>
            <%= f.text_field :content %>
          </div>
          <%= f.submit 'Post', class: 'button' %>
        <% end %>
      <% end %>
      <% unless @wall_feed.empty? %>
        <% @wall_feed.each do |item| %>
          <div class="row alert-box secondary">
            <p class="large-3 columns"><%= item.user.name %> 
              <% if item.type == 'WallPost' %> 
                posted on <%= item.friend.name %>'s wall
              <% end %>
            </p>
            <p class="large-6 columns"><%= item.content %></p>
            <p class="large-3 columns"><%= item.created_at.strftime("Posted at %H:%M") %></p>
          </div>
        <% end %>
      <% end %>
    </section>
  </div>